<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PaymentShippingDataService\PaymentShippingDataService.csproj" />
    <ProjectReference Include="..\PaymentShippingModel\PaymentShippingModel.csproj" />
    <ProjectReference Include="..\PaymentShippingService\PaymentShippingService.csproj" />
  </ItemGroup>

</Project>
